"use client";

import { useEffect, useMemo, useState } from "react";
import { ArrowRightCircle, BarChart3, Download, Plus, Users } from "lucide-react";
import { Topbar } from "@/components/layout/Topbar";
import { Card } from "@/components/ui/Card";
import { Button } from "@/components/ui/Button";
import { Loader } from "@/components/common/Loader";
import { CreateOpeningModal } from "@/components/recruitment/CreateOpeningModal";
import { AddCandidateModal } from "@/components/recruitment/AddCandidateModal";
import { ConversionResultModal } from "@/components/recruitment/ConversionResultModal";
import { recruitmentService } from "@/services/recruitment.service";
import type { Candidate, CandidateConvertResult, CandidateStage, JobOpening, JobOpeningStatus } from "@/types";

const STAGES: CandidateStage[] = ["applied", "shortlisted", "interview", "offer_extended", "rejected"];
const STAGE_STYLE: Record<string,string> = { applied:"bg-gray-100 text-gray-700", shortlisted:"bg-blue-50 text-blue-700", interview:"bg-amber-50 text-amber-700", offer_extended:"bg-purple-50 text-purple-700", hired:"bg-green-50 text-green-700", rejected:"bg-red-50 text-red-700" };

export default function RecruitmentPage() {
  const [openings,setOpenings]=useState<JobOpening[]>([]), [selectedOpeningId,setSelectedOpeningId]=useState(""), [candidates,setCandidates]=useState<Candidate[]>([]);
  const [loading,setLoading]=useState(false), [error,setError]=useState<string|null>(null), [showCreateOpening,setShowCreateOpening]=useState(false), [showAddCandidate,setShowAddCandidate]=useState(false), [conversionResult,setConversionResult]=useState<CandidateConvertResult|null>(null);
  const loadOpenings=()=>recruitmentService.listOpenings().then(list=>{setOpenings(list);if(list.length&&!selectedOpeningId)setSelectedOpeningId(list[0].id);});
  const loadCandidates=(id:string)=>{setLoading(true);recruitmentService.listCandidates(id).then(setCandidates).catch(()=>setError("Could not load candidates.")).finally(()=>setLoading(false));};
  useEffect(()=>{loadOpenings();},[]); useEffect(()=>{if(selectedOpeningId)loadCandidates(selectedOpeningId);},[selectedOpeningId]);
  const counts=useMemo(()=>Object.fromEntries(STAGES.map(s=>[s,candidates.filter(c=>c.stage===s).length])),[candidates]);
  const conversionRate=candidates.length?Math.round(((counts.hired??0)+(counts.offer_extended??0))/candidates.length*100):0;
  const handleStageChange=async(id:string,stage:CandidateStage)=>{try{await recruitmentService.updateStage(id,stage);loadCandidates(selectedOpeningId);}catch{setError("Could not update candidate stage.");}};
  const handleOpeningStatusChange=async(id:string,status:JobOpeningStatus)=>{try{await recruitmentService.updateOpeningStatus(id,status);loadOpenings();}catch{setError("Could not update opening status.");}};
  const handleConvert=async(id:string)=>{try{setConversionResult(await recruitmentService.convert(id));loadCandidates(selectedOpeningId);}catch(err:any){setError(err?.response?.data?.detail??"Could not convert candidate.");}};
  return <><Topbar title="Recruitment" subtitle="Talent pipeline, openings & interview flow"/><div className="space-y-6 p-8">
    <div className="grid grid-cols-2 gap-4 lg:grid-cols-4"><Metric icon={Users} label="Candidates" value={candidates.length}/><Metric icon={BarChart3} label="Interviews" value={counts.interview??0}/><Metric icon={Users} label="Offers" value={counts.offer_extended??0}/><Metric icon={BarChart3} label="Pipeline conversion" value={conversionRate} suffix="%"/></div>
    <div className="flex flex-wrap items-center justify-between gap-3"><div className="flex gap-2"><select value={selectedOpeningId} onChange={e=>setSelectedOpeningId(e.target.value)} className="rounded-xl border border-gray-200 px-3 py-2 text-sm">{openings.map(o=><option key={o.id} value={o.id}>{o.title} · {o.department}</option>)}</select>{selectedOpeningId&&<select value={openings.find(o=>o.id===selectedOpeningId)?.status??"open"} onChange={e=>handleOpeningStatusChange(selectedOpeningId,e.target.value as JobOpeningStatus)} className="rounded-xl border border-gray-200 px-3 py-2 text-xs"><option value="open">Open</option><option value="on_hold">On hold</option><option value="closed">Closed</option></select>}</div><div className="flex gap-2"><Button variant="secondary" onClick={()=>setShowCreateOpening(true)} className="flex items-center gap-2"><Plus size={15}/> New opening</Button>{selectedOpeningId&&<Button onClick={()=>setShowAddCandidate(true)} className="flex items-center gap-2"><Plus size={15}/> Add candidate</Button>}</div></div>
    {error&&<p className="text-sm text-red-500">{error}</p>}
    {openings.length===0?<Card className="py-16 text-center text-gray-400">No openings yet. Create your first hiring pipeline.</Card>:loading?<Loader label="Loading candidates..."/>:<>
      <div className="grid grid-cols-1 gap-4 xl:grid-cols-5">{STAGES.map(stage=><div key={stage} className="rounded-2xl border border-gray-200 bg-gray-50/60 p-3 min-h-[260px]"><div className="mb-3 flex items-center justify-between"><p className="text-xs font-semibold capitalize text-gray-700">{stage.replace(/_/g," ")}</p><span className="rounded-full bg-white px-2 py-0.5 text-[10px] font-semibold text-gray-500">{counts[stage]??0}</span></div><div className="space-y-2">{candidates.filter(c=>c.stage===stage).map(c=><div key={c.id} className="rounded-xl border border-gray-200 bg-white p-3 shadow-sm"><p className="text-sm font-medium text-gray-900">{c.full_name}</p><p className="mt-1 truncate text-[11px] text-gray-400">{c.email}</p><div className="mt-3 flex items-center justify-between gap-2">{c.resume_file_name?<button onClick={()=>recruitmentService.downloadResume(c.id,c.resume_file_name!)} className="text-gray-400 hover:text-brand"><Download size={14}/></button>:<span/>}{stage!=="rejected"&&<select value={c.stage} onChange={e=>handleStageChange(c.id,e.target.value as CandidateStage)} className={`max-w-[120px] rounded-lg border-0 px-2 py-1 text-[10px] font-medium ${STAGE_STYLE[c.stage]}`}><option value={c.stage}>{c.stage.replace(/_/g," ")}</option>{STAGES.filter(s=>s!==c.stage).map(s=><option key={s} value={s}>{s.replace(/_/g," ")}</option>)}</select>}</div>{stage==="offer_extended"&&<button onClick={()=>handleConvert(c.id)} className="mt-2 flex items-center gap-1 text-xs font-medium text-brand"><ArrowRightCircle size={13}/> Convert to employee</button>}</div>)}{(counts[stage]??0)===0&&<div className="rounded-xl border border-dashed border-gray-200 bg-white/60 p-6 text-center text-[11px] text-gray-400">No candidates</div>}</div></div>)}</div>
      <Card className="p-5"><div className="mb-4"><p className="text-sm font-semibold text-gray-900">Pipeline analytics</p><p className="text-xs text-gray-400">Current opening distribution</p></div><div className="flex h-3 overflow-hidden rounded-full bg-gray-100">{STAGES.filter(s=>(counts[s]??0)>0).map(s=><div key={s} className="h-full" style={{width:`${(counts[s]/candidates.length)*100}%`}} title={`${s}: ${counts[s]}`}/>)}</div><div className="mt-4 flex flex-wrap gap-4 text-xs text-gray-500">{STAGES.map(s=><span key={s}><b className="text-gray-800">{counts[s]??0}</b> {s.replace(/_/g," ")}</span>)}</div></Card>
    </>}
  </div>{showCreateOpening&&<CreateOpeningModal onClose={()=>setShowCreateOpening(false)} onCreated={loadOpenings}/>} {showAddCandidate&&selectedOpeningId&&<AddCandidateModal openingId={selectedOpeningId} onClose={()=>setShowAddCandidate(false)} onAdded={()=>loadCandidates(selectedOpeningId)}/>} {conversionResult&&<ConversionResultModal result={conversionResult} onClose={()=>setConversionResult(null)}/>}</>;
}
function Metric({icon:Icon,label,value,suffix=""}:{icon:any;label:string;value:number;suffix?:string}){return <Card className="p-4"><div className="rounded-xl bg-gray-100 p-2 w-fit"><Icon size={17} className="text-gray-600"/></div><p className="mt-3 text-xs text-gray-500">{label}</p><p className="mt-1 text-2xl font-semibold text-gray-900">{value}{suffix}</p></Card>}
