"""add notice period and conversion status

Revision ID: 9370cce6ed2f
Revises: b16830938f8d
Create Date: 2026-07-28 07:18:57.183390
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9370cce6ed2f'
down_revision: Union[str, None] = 'b16830938f8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
